# Snakemake command:
# snakemake --cores 1 results/B.bam


rule bwa_mem:
    '''
    Align any fastq reads file in 'data/sample' to the assembly 'data/genome.fa'.
    '''
    input:
        assembly = 'data/genome.fa',
        reads = 'data/samples/{sample}.fastq'
    output:
        'results/{sample}.bam'
    shell:
        'bwa mem {input.assembly} {input.reads} | samtools view -b > {output}'
